drm/amdgpu/virt: fix the build
drivers/gpu/drm/amd/amdgpu/amdgpu_virt.c: In function ‘amdgpu_virt_init_data_exchange’:
drivers/gpu/drm/amd/amdgpu/amdgpu_virt.c:586:10: error: ‘struct amdgpu_device’ has no member named ‘fw_vram_usage’
  586 |  if (adev->fw_vram_usage.va != NULL) {
      |          ^~
drivers/gpu/drm/amd/amdgpu/amdgpu_virt.c:591:9: error: ‘struct amdgpu_device’ has no member named ‘fw_vram_usage’
  591 |    (adev->fw_vram_usage.va + (AMD_SRIOV_MSG_PF2VF_OFFSET_KB << 10));
      |         ^~
drivers/gpu/drm/amd/amdgpu/amdgpu_virt.c:594:9: error: ‘struct amdgpu_device’ has no member named ‘fw_vram_usage’
  594 |    (adev->fw_vram_usage.va + (AMD_SRIOV_MSG_VF2PF_OFFSET_KB << 10));
      |         ^~
make[4]: *** [scripts/Makefile.build:283: drivers/gpu/drm/amd/amdgpu/amdgpu_virt.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [scripts/Makefile.build:500: drivers/gpu/drm/amd/amdgpu] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:500: drivers/gpu/drm] Error 2
make[1]: *** [scripts/Makefile.build:500: drivers/gpu] Error 2
make: *** [Makefile:1788: drivers] Error 2

Cc: Bokun Zhang <Bokun.Zhang@amd.com>
Fixes: 614e7ac92979 ("drm/amdgpu: Implement new guest side VF2PF message transaction")
Reviewed-and-tested-by: Evan Quan <evan.quan@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>